title:               Chelsea FC Performance Insights Competition
url:                 https://chelsea-fc-performance-insights.github.io/Competition/
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Chelsea FC
  url:               https://chelsea-fc-performance-insights.github.io/Competition/
  email:             test

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
